export enum NotificationType {
  LINE_EXPIRATION = 'LINE_EXPIRATION',
  INVOICE_DUE = 'INVOICE_DUE',
  SIM_ASSIGNMENT = 'SIM_ASSIGNMENT',
  ACCOUNT_UPDATE = 'ACCOUNT_UPDATE',
  LINE_EXPIRING_SOON = 'LINE_EXPIRING_SOON',
  GENERAL = 'GENERAL',
}