###Lista de todas las peticiones
GET http://localhost:5006/reports

###Create a new message
POST http://localhost:5006/reports
content-type: application/json
///dejar unaline vacia es importante para hacer los post aqui

{
    "id": 4,
    "idcomisione": 1
}

###DELETE a user given id
///se elimina dado su id

DELETE http://localhost:5006/reports/buscar-por-comisione//25


###Implementa la lógica para buscar por idplan en tu servicio
http://localhost:5006/reports/buscar-por-comisione/1









###Implementa la lógica para buscar por idcompaniclient en tu servicio
http://localhost:5006/pago-de-clientes/buscar-por-compania/0


###busqueda por idsim
http://localhost:5006/pago-de-clientes/buscar-por-sim/4


###busqueda por idmexpago
http://localhost:5006/pago-de-clientes/buscar-por-mexpago/30

###GET a particular pago de cliente
///es un llamado por id
GET http://localhost:5006/pago-de-clientes/3


###GET a todos los id con una comision determinado
///es un llamado hacierto id
GET http://localhost:5006/comisiones?comision=15


###Update a comision
//se busca por id al que sele dese cambiar la comision
PATCH http://localhost:5006/comisiones/3
Content-Type: application/json

{
    "comision": "15"
}